version: "3.1"
services:
    www:
        build: .
        ports:
            - "8001:80"
        links:
            - db
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: bookstore
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
